In [1]:
import pandas as pd

In [2]:
content = pd.read_csv('D:\Github_project\data\movie_comments.csv')

C:\Users\Ryan Wu\Anaconda3\envs\ai\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (0,4) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
content.head()

id                                        link name  \
0  1  https://movie.douban.com/subject/26363254/  战狼2   
1  2  https://movie.douban.com/subject/26363254/  战狼2   
2  3  https://movie.douban.com/subject/26363254/  战狼2   
3  4  https://movie.douban.com/subject/26363254/  战狼2   
4  5  https://movie.douban.com/subject/26363254/  战狼2   

                                             comment star  
0                                 吴京意淫到了脑残的地步，看了恶心想吐    1  
1  首映礼看的。太恐怖了这个电影，不讲道理的，完全就是吴京在实现他这个小粉红的英雄梦。各种装备轮...    2  
2  吴京的炒作水平不输冯小刚，但小刚至少不会用主旋律来炒作…吴京让人看了不舒服，为了主旋律而主旋...    2  
3                      凭良心说，好看到不像《战狼1》的续集，完虐《湄公河行动》。    4  
4                                               中二得很    1

In [4]:
content.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 261497 entries, 0 to 261496
Data columns (total 5 columns):
id         261497 non-null object
link       261497 non-null object
name       261497 non-null object
comment    261495 non-null object
star       261497 non-null object
dtypes: object(5)
memory usage: 10.0+ MB


In [5]:
content.dropna(subset=['comment'], inplace=True)

In [6]:
content.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 261495 entries, 0 to 261496
Data columns (total 5 columns):
id         261495 non-null object
link       261495 non-null object
name       261495 non-null object
comment    261495 non-null object
star       261495 non-null object
dtypes: object(5)
memory usage: 12.0+ MB


In [7]:
content.drop_duplicates(subset=['comment'], inplace=True)

In [8]:
content.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 213970 entries, 0 to 261496
Data columns (total 5 columns):
id         213970 non-null object
link       213970 non-null object
name       213970 non-null object
comment    213970 non-null object
star       213970 non-null object
dtypes: object(5)
memory usage: 9.8+ MB


In [9]:
set(content.star)

{1, '1', 2, '2', 3, '3', 4, '4', '5', 5, 'star'}

In [10]:
content.drop(content[content.star=='star'].index, inplace=True)

In [11]:
content.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 213969 entries, 0 to 261496
Data columns (total 5 columns):
id         213969 non-null object
link       213969 non-null object
name       213969 non-null object
comment    213969 non-null object
star       213969 non-null object
dtypes: object(5)
memory usage: 9.8+ MB


In [12]:
set(content.star)

{1, '1', 2, '2', 3, '3', 4, '4', '5', 5}

In [13]:
y = [int(star) for star in content.star]

In [14]:
comments = content.comment

In [15]:
len(y), len(comments)

(213969, 213969)

## 词向量相加构建句向量

In [16]:
import jieba
def cut(string): return ' '.join(jieba.cut(string))

In [17]:
import re
def token(string):
    return re.findall(r'[\d|\w]+', string)

In [18]:
comments_cut = [cut(''.join(token(comment))) for comment in comments]

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\RYANWU~1\AppData\Local\Temp\jieba.cache
Loading model cost 1.214 seconds.
Prefix dict has been built succesfully.


In [19]:
comments_cut[0].split()

['吴京', '意淫', '到', '了', '脑残', '的', '地步', '看', '了', '恶心', '想', '吐']

In [20]:
# 采用之前维基百科+新闻语料训练的词向量
from gensim.models.word2vec import Word2Vec
word2vec = Word2Vec.load(r'D:\Github_project\common-data\词向量\news_word2vec.w2v').wv

In [24]:
len(word2vec.vocab)

616395

In [21]:
word2vec.wv['中二'].shape

C:\Users\Ryan Wu\Anaconda3\envs\ai\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """Entry point for launching an IPython kernel.


(500,)

In [26]:
import numpy as np

In [27]:
np.zeros(500, None) + word2vec.wv['中二']

C:\Users\Ryan Wu\Anaconda3\envs\ai\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """Entry point for launching an IPython kernel.


array([-2.34566391e-01,  2.79686805e-02,  4.15266939e-02, -1.78346932e-01,
        1.02283709e-01,  9.09975618e-02, -8.90697166e-02, -9.23506841e-02,
       -1.94960028e-01,  2.81524897e-01, -2.67716378e-01,  3.56442302e-01,
       -1.56728461e-01,  1.41186714e-01, -4.05162051e-02, -3.29683810e-01,
        1.43675506e-01,  2.80216038e-02,  8.96399096e-02, -1.10607661e-01,
       -5.41270664e-03, -2.17700794e-01, -1.87995419e-01, -6.25246391e-02,
        3.53753656e-01,  1.66690182e-02,  1.82034761e-01,  1.33014679e-01,
       -1.18101671e-01, -1.40211239e-01,  2.02820256e-01, -3.42190489e-02,
       -1.96076140e-01, -2.19466701e-01,  9.41848755e-02, -7.00309873e-02,
       -1.09779820e-01, -1.05037972e-01, -2.15431079e-01,  2.40143076e-01,
       -2.14520514e-01, -3.69605832e-02,  9.37635377e-02,  1.88759536e-01,
        3.43713313e-01, -1.39666110e-01,  6.32417575e-02, -3.31544608e-01,
       -3.61580737e-02, -1.49203002e-01,  1.72923356e-02, -4.85782363e-02,
        2.10080639e-01,  

In [28]:
def sentence2vec(sentences):
    sentence_vecs = []
    for sentence in sentences:
        s = 0
        sentence_vec = np.zeros(500, None)
        words = sentence.split()
        for word in words:
            if word in word2vec.vocab:
                sentence_vec += word2vec.wv[word]
                s += 1
            else:
                continue
        if s != 0:
            sentence_vec = sentence_vec / s
        else:
            sentence_vec = np.zeros(500, None)
        sentence_vecs.append(sentence_vec)
    return sentence_vecs 

In [29]:
sentence_vecs = sentence2vec(comments_cut)

C:\Users\Ryan Wu\Anaconda3\envs\ai\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  if __name__ == '__main__':


In [30]:
sentence_vecs[0].shape

(500,)

In [31]:
len(sentence_vecs), len(y)

(213969, 213969)

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(sentence_vecs, y, test_size=0.2, random_state=42)

In [33]:
len(X_train), len(X_test), len(y_train), len(y_test)

(171175, 42794, 171175, 42794)

In [34]:
import numpy as np
X_tr_arr = np.array(X_train, dtype='float32')
X_ts_arr = np.array(X_test, dtype='float32')
y_tr_arr = np.array(y_train)
y_ts_arr = np.array(y_test)

In [35]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression().fit(X_tr_arr, y_tr_arr)

C:\Users\Ryan Wu\Anaconda3\envs\ai\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Ryan Wu\Anaconda3\envs\ai\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [36]:
clf.score(X_tr_arr, y_tr_arr)

0.401992113334307

In [37]:
clf.score(X_ts_arr, y_ts_arr)

0.39881759125111

In [38]:
X_tr_arr.shape

(171175, 500)

In [39]:
y_tr_arr.shape

(171175,)

In [40]:
y_tr_arr[0]

2

In [41]:
num_labels = 6

def reformat(labels):
  # Map 1 to [0.0, 1.0, 0.0 ...], 2 to [0.0, 0.0, 1.0 ...]
  labels = (np.arange(num_labels) == labels[:,None]).astype(np.float32)
  return labels

In [42]:
y_tr_arr = reformat(y_tr_arr)
y_ts_arr = reformat(y_ts_arr)
print('Training set', X_tr_arr.shape, y_tr_arr.shape)
print('Test set', X_ts_arr.shape, y_ts_arr.shape)

Training set (171175, 500) (171175, 6)
Test set (42794, 500) (42794, 6)


In [43]:
y_tr_arr[0]

array([0., 0., 1., 0., 0., 0.], dtype=float32)

In [44]:
X_tr_arr[0].shape

(500,)

In [45]:
import tensorflow as tf

In [46]:
def accuracy(predictions, labels):
  return (100.0 * np.sum(np.argmax(predictions, 1) == np.argmax(labels, 1))
          / predictions.shape[0])

In [58]:
batch_size = 100
hiden_layer_node_num = 1024
beta = 0.01

graph = tf.Graph()
with graph.as_default():

  # Input data. For the training data, we use a placeholder that will be fed
  # at run time with a training minibatch.
  tf_train_dataset = tf.placeholder(tf.float32,
                                    shape=(batch_size, 500))
  tf_train_labels = tf.placeholder(tf.float32, shape=(batch_size, num_labels))
  tf_test_dataset = tf.constant(X_ts_arr)
  
  # Variables.
  weights1 = tf.Variable(
    tf.truncated_normal([500, hiden_layer_node_num], stddev=0.04))
  biases1 = tf.Variable(tf.zeros([hiden_layer_node_num]))
    
  # input layer output (batch_size, hiden_layer_node_num)
  weights2 = tf.Variable(tf.truncated_normal([hiden_layer_node_num, num_labels], stddev=0.04))
  biases2 = tf.Variable(tf.zeros([num_labels]))

  
  # Training computation.
  logits = tf.matmul(tf.nn.relu(tf.matmul(tf_train_dataset, weights1) + biases1), weights2) + biases2
  loss = tf.reduce_mean(
    tf.nn.softmax_cross_entropy_with_logits(labels=tf_train_labels, logits=logits))
  regularizers = tf.nn.l2_loss(weights1) + tf.nn.l2_loss(weights2)
  loss = tf.reduce_mean(loss + beta * regularizers)
  
  # Optimizer.
  optimizer = tf.train.GradientDescentOptimizer(0.5).minimize(loss)
  
  # Predictions for the training, validation, and test data.
  train_prediction = tf.nn.softmax(logits)
  test_prediction = tf.nn.softmax(tf.matmul(tf.nn.relu(tf.matmul(tf_test_dataset, weights1) + biases1), weights2) + biases2)

In [59]:
num_steps = 3001

with tf.Session(graph=graph) as session:
  tf.global_variables_initializer().run()
  print("Initialized")
  for step in range(num_steps):
    # Pick an offset within the training data, which has been randomized.
    # Note: we could use better randomization across epochs.
    offset = (step * batch_size) % (y_tr_arr.shape[0] - batch_size)
    # Generate a minibatch.
    batch_data = X_tr_arr[offset:(offset + batch_size), :]
    batch_labels = y_tr_arr[offset:(offset + batch_size), :]
    # Prepare a dictionary telling the session where to feed the minibatch.
    # The key of the dictionary is the placeholder node of the graph to be fed,
    # and the value is the numpy array to feed to it.
    feed_dict = {tf_train_dataset : batch_data, tf_train_labels : batch_labels}
    _, l, predictions = session.run(
      [optimizer, loss, train_prediction], feed_dict=feed_dict)
    if (step % 500 == 0):
      print("Minibatch loss at step %d: %f" % (step, l))
      print("Minibatch accuracy: %.1f%%" % accuracy(predictions, batch_labels))
  print("Test accuracy: %.1f%%" % accuracy(test_prediction.eval(), y_ts_arr))

Initialized
Minibatch loss at step 0: 5.017567
Minibatch accuracy: 12.0%
Minibatch loss at step 500: 1.567699
Minibatch accuracy: 30.0%
Minibatch loss at step 1000: 1.472009
Minibatch accuracy: 36.0%
Minibatch loss at step 1500: 1.574567
Minibatch accuracy: 31.0%
Minibatch loss at step 2000: 1.499942
Minibatch accuracy: 35.0%
Minibatch loss at step 2500: 1.455968
Minibatch accuracy: 33.0%
Minibatch loss at step 3000: 1.469914
Minibatch accuracy: 41.0%
Test accuracy: 34.8%


## 以上效果不佳，试试情感分类工具snownlp

In [204]:
from snownlp import SnowNLP

In [205]:
s = SnowNLP(u'这个东西真赞。但是我不喜欢')

In [206]:
s.sentiments

0.9269068736444782

In [209]:
s = SnowNLP(u'恶心')

In [210]:
s.sentiments

0.12413793103448256

In [211]:
comments[0]

'吴京意淫到了脑残的地步，看了恶心想吐'

In [212]:
SnowNLP(comments[0]).sentiments

0.0323066138237218

In [213]:
sentiments = [SnowNLP(comment).sentiments for comment in comments]

In [214]:
sentiments[0]

0.0323066138237218

In [215]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(sentiments, y, test_size=0.2, random_state=42)

In [216]:
import numpy as np
X_tr_arr = np.array(X_train, dtype='float32')
X_ts_arr = np.array(X_test, dtype='float32')
y_tr_arr = np.array(y_train)
y_ts_arr = np.array(y_test)

In [220]:
X_tr_arr.shape, y_tr_arr.shape, X_ts_arr.shape, y_ts_arr.shape

((171175,), (171175,), (42794,), (42794,))

In [221]:
X_tr_arr[0]

0.99956065

In [222]:
y_tr_arr[0]

2

In [223]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression().fit(X_tr_arr.reshape(-1, 1), y_tr_arr)

C:\Users\Mr. Wu\Anaconda3\envs\AI\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mr. Wu\Anaconda3\envs\AI\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [225]:
clf.score(X_tr_arr.reshape(-1, 1), y_tr_arr)

0.33087191470717103

In [226]:
clf.score(X_ts_arr.reshape(-1, 1), y_ts_arr)

0.32983595831191287

## fasttext

In [1]:
import fasttext

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(comments, y, test_size=0.2, random_state=42)

In [ ]:
len(X_train), len(X_test), len(y_train), len(y_test)

In [67]:
with open('comments_with_label.txt', 'w', encoding='utf-8') as f:
    for comment, label in zip(X_train, y_train):
        label = str('__label__' + str(label))
        comment = cut(comment)
        f.write(label + ' , ' + comment)
        f.write('\n')

In [80]:
model = fasttext.train_supervised(input="comments_with_label.txt", lr=0.1, epoch=50, wordNgrams=3)

In [72]:
with open('comments_test.txt', 'w', encoding='utf-8') as f:
     for comment, label in zip(X_test, y_test):
        label = str('__label__' + str(label))
        comment = cut(comment)
        f.write(label + ' , ' + comment)
        f.write('\n')

In [81]:
model.test('comments_test.txt')

(42794, 0.4331448333878581, 0.4331448333878581)

## 词向量+GRU

In [23]:
import numpy as np
np.random.seed(42)
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score

from keras.models import Model
from keras.layers import Input, Dense, Embedding, SpatialDropout1D, concatenate
from keras.layers import GRU, Bidirectional, GlobalAveragePooling1D, GlobalMaxPooling1D
from keras.preprocessing import text, sequence
from keras.callbacks import Callback

import warnings
warnings.filterwarnings('ignore')

import os
os.environ['OMP_NUM_THREADS'] = '4'

Using TensorFlow backend.


In [36]:
comments_cut[0]

'吴京 意淫 到 了 脑残 的 地步 看 了 恶心 想 吐'

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(comments_cut, y, test_size=0.2, random_state=42)

In [39]:
len(X_train), len(X_test), len(y_train), len(y_test)

(171175, 42794, 171175, 42794)

In [57]:
y_train = np.array(y_train)
y_test = np.array(y_test)

In [58]:
num_labels = 5

def reformat(labels):
  # Map 1 to [1.0, 0.0, 0.0 ...], 2 to [0.0, 1.0, 0.0 ...]
  labels = (np.arange(num_labels) == (labels[:,None]-1)).astype(np.float32)
  return labels

In [59]:
y_train = reformat(y_train)
y_test = reformat(y_test)

In [60]:
max_features = 30000
maxlen = 100
embed_size = 500

tokenizer = text.Tokenizer(num_words=max_features)
tokenizer.fit_on_texts(list(X_train) + list(X_test))
X_train = tokenizer.texts_to_sequences(X_train)
X_test = tokenizer.texts_to_sequences(X_test)
x_train = sequence.pad_sequences(X_train, maxlen=maxlen)
x_test = sequence.pad_sequences(X_test, maxlen=maxlen)

In [61]:
x_train[0]

array([    0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,   161,  1719,   145,    79,   359,
           8,    19,  1386,    19,  1337,   153,     1,  3007,   441,
          26,  3814,   491,     1, 13828,     2,     8,   568,  2287,
         135,    48,    23,   836,   383, 17991,  1592,    10,   142,
        5166,    15,    32,   542,  6307,    21,   247,    12,   286,
        4155])

In [62]:
word_index = tokenizer.word_index
nb_words = min(max_features, len(word_index))
embedding_matrix = np.zeros((nb_words, embed_size))

In [75]:
for word, i in word_index.items():
    if i >= max_features: continue
    if word in word2vec.vocab:
        embedding_vector = word2vec.wv[word]
        embedding_matrix[i] = embedding_vector

In [85]:
embedding_matrix[2]

array([-9.82367471e-02, -2.09654644e-02,  1.02359004e-01,  1.26379028e-01,
        4.47619408e-02, -6.26963675e-02, -9.53782499e-02,  1.17928050e-02,
       -5.34206592e-02, -1.65859148e-01,  1.31364122e-01, -1.88644320e-01,
       -5.18909134e-02,  1.57583311e-01,  3.69974151e-02,  6.09869435e-02,
        1.07551791e-01, -5.45741953e-02,  2.83474848e-02,  1.02960937e-01,
        8.17340612e-02,  5.57441860e-02,  1.12398140e-01, -5.55605581e-03,
       -5.53949252e-02,  1.60115153e-01,  2.57600006e-03,  2.61549085e-01,
       -1.99222821e-03,  8.45237598e-02, -6.81143776e-02,  1.69387072e-01,
        2.26114485e-02,  2.46438477e-02,  3.83693911e-02,  3.74534838e-02,
       -1.67340443e-01, -2.77866330e-02, -3.19582112e-02,  2.33958159e-02,
       -9.91796255e-02,  2.91199535e-01, -5.37674949e-02,  6.06040321e-02,
        5.34891970e-02, -3.88256349e-02,  1.15983509e-01, -1.64635584e-01,
        5.50174788e-02, -2.36537438e-02,  2.53487695e-02,  1.04953408e-01,
        2.70001125e-02,  

In [76]:
class RocAucEvaluation(Callback):
    def __init__(self, validation_data=(), interval=1):
        super(Callback, self).__init__()

        self.interval = interval
        self.X_val, self.y_val = validation_data

    def on_epoch_end(self, epoch, logs={}):
        if epoch % self.interval == 0:
            y_pred = self.model.predict(self.X_val, verbose=0)
            # verbose = 0 为不在标准输出流输出日志信息
            score = roc_auc_score(self.y_val, y_pred)
            print("\n ROC-AUC - epoch: %d - score: %.6f \n" % (epoch+1, score))

In [77]:
def get_model():
    inp = Input(shape=(maxlen, ))
    x = Embedding(max_features, embed_size, weights=[embedding_matrix])(inp)
    x = SpatialDropout1D(0.2)(x)
    x = Bidirectional(GRU(80, return_sequences=True))(x)
    avg_pool = GlobalAveragePooling1D()(x)
    max_pool = GlobalMaxPooling1D()(x)
    conc = concatenate([avg_pool, max_pool])
    outp = Dense(5, activation="sigmoid")(conc)
    
    model = Model(inputs=inp, outputs=outp)
    model.compile(loss='binary_crossentropy',
                  optimizer='adam',
                  metrics=['accuracy'])

    return model

In [78]:
model = get_model()


batch_size = 32
epochs = 2


RocAuc = RocAucEvaluation(validation_data=(x_test, y_test), interval=1)

hist = model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_data=(x_test, y_test),
                 callbacks=[RocAuc], verbose=2)



Train on 171175 samples, validate on 42794 samples
Epoch 1/2


AlreadyExistsError: Resource __per_step_25/training_1/Adam/gradients/bidirectional_4/while/ReadVariableOp/Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
	 [[{{node training_1/Adam/gradients/bidirectional_4/while/ReadVariableOp/Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var}}]]