# 1. Basics

## PyTorch Basics

In [15]:
import torch 

In [16]:
import torchvision

In [17]:
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms

In [18]:
# ================================================================== #
#                         Table of Contents                          #
# ================================================================== #

# 1. Basic autograd example 1               (Line 25 to 39)
# 2. Basic autograd example 2               (Line 46 to 83)
# 3. Loading data from numpy                (Line 90 to 97)
# 4. Input pipline                          (Line 104 to 129)
# 5. Input pipline for custom dataset       (Line 136 to 156)
# 6. Pretrained model                       (Line 163 to 176)
# 7. Save and load model                    (Line 183 to 189) 

In [19]:
# ================================================================== #
#                     1. Basic autograd example 1                    #
# ================================================================== #

In [20]:
# Create tensors.
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

In [21]:
# Build a computational graph.
y = w * x + b    # y = 2 * x + 3

In [22]:
# Compute gradients.
y.backward()

In [23]:
# Print out the gradients.
print(x.grad)    # x.grad = 2 
print(w.grad)    # w.grad = 1 
print(b.grad)    # b.grad = 1 

tensor(2.)
tensor(1.)
tensor(1.)


In [24]:
# ================================================================== #
#                    2. Basic autograd example 2                     #
# ================================================================== #

In [25]:
# Create tensors of shape (10, 3) and (10, 2).
x = torch.randn(10, 3)
y = torch.randn(10, 2)

In [30]:
# Build a fully connected layer.
linear = nn.Linear(3, 2)
print ('w: ', linear.weight)
print ('b: ', linear.bias)

w:  Parameter containing:
tensor([[ 0.0837, -0.0566, -0.1824],
        [-0.0610,  0.1406, -0.1115]], requires_grad=True)
b:  Parameter containing:
tensor([ 0.3320, -0.4430], requires_grad=True)


In [31]:
# Build loss function and optimizer.
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

In [32]:
# Forward pass.
pred = linear(x)

In [33]:
# Compute loss.
loss = criterion(pred, y)
print('loss: ', loss.item())

loss:  1.037523865699768


In [34]:
# Backward pass.
loss.backward()

In [35]:
# Print out the gradients.
print ('dL/dw: ', linear.weight.grad) 
print ('dL/db: ', linear.bias.grad)

dL/dw:  tensor([[ 0.0584,  0.1252,  0.0701],
        [-0.0163, -0.7110, -0.2468]])
dL/db:  tensor([ 0.0728, -0.6428])


In [36]:
# 1-step gradient descent.
optimizer.step()

In [37]:
# You can also perform gradient descent at the low level.
# linear.weight.data.sub_(0.01 * linear.weight.grad.data)
# linear.bias.data.sub_(0.01 * linear.bias.grad.data)

# Print out the loss after 1-step gradient descent.
pred = linear(x)
loss = criterion(pred, y)
print('loss after 1 step optimization: ', loss.item())

loss after 1 step optimization:  1.027516484260559


In [38]:
# ================================================================== #
#                     3. Loading data from numpy                     #
# ================================================================== #

In [39]:
# Create a numpy array.
x = np.array([[1, 2], [3, 4]])

# Convert the numpy array to a torch tensor.
y = torch.from_numpy(x)

# Convert the torch tensor to a numpy array.
z = y.numpy()

In [43]:
y

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [41]:
z

array([[1, 2],
       [3, 4]])

In [ ]:
# ================================================================== #
#                         4. Input pipline                           #
# ================================================================== #

# Download and construct CIFAR-10 dataset.
train_dataset = torchvision.datasets.CIFAR10(root='../../data/',
                                             train=True, 
                                             transform=transforms.ToTensor(),
                                             download=True)

# Fetch one data pair (read data from disk).
image, label = train_dataset[0]
print (image.size())
print (label)


79.8%

In [ ]:
z